version: "3"
services:
  servicediscovery:
    image: "msc-servicediscovery"
    ports:
     - "8761:8761"
  configserver:
    image: "msc-configserver"
    ports:
     - "8888:8888"
    depends_on:
     - servicediscovery
  bookws:
    image: "msc-booksservice"
    ports:
     - "9002:9002"
    depends_on:
     - configserver
     - servicediscovery



