version: "3.7"

services:

  eurekaserver:
    image: msc-servicediscovery
    ports:
      - "8761:8761"
    environment:
      - "PORT=8761"

  configserver:
    image: msc-configserver
    ports:
      - "8888:8888"
    environment:
      - "PORT=8888"
      - "PROFILE:default"
      - "GITPASSWORD=.[]/Nvf3388GiT"
      - "EUREKASERVER_PORT=8761"
      - "EUREKA_DEFAULT_ZONE=http://eurekaserver:8761/eureka/"
      - "KEYSTORE_PASSWORD=foobar"
      - "KEY_PASSWORD=config"

  booksservice:
    image: msc-booksservice
    ports:
      - "9010:9010"
    environment:
      - "PORT=9010"
      - "PROFILE=default"
      - "EUREKASERVER_PORT=8761"
      - "CONFIGSERVER_PORT=8888"
      - "EUREKA_DEFAULT_ZONE=http://eurekaserver:8761/eureka/"

  stockservice:
    image: msc-stockservice
    ports:
      - "9020:9020"
    environment:
      - "PORT=9020"
      - "PROFILE=default"
      - "EUREKASERVER_PORT=8761"
      - "CONFIGSERVER_PORT=8888"
      - "EUREKA_DEFAULT_ZONE=http://eurekaserver:8761/eureka/"